openapi: "3.0.0"
info:
  title: Simple API overview
  version: 1.0.0
paths:
  /test:
    get:
      operationId: testRequestsv1
      summary: Test API Requests
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              examples: 
                foo:
                  value:
                    {
                      "versions": [
                        {
                            "status": "CURRENT",
                            "updated": "2011-01-21T11:33:21Z",
                            "id": "v1.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8080/v1/",
                                    "rel": "self"
                                }
                            ]
                        },
                      ]
                    }