name: Tests

on:
  push:
  pull_request:
env:
  GOPRIVATE: "github.com/speakeasy-api"
jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        go-version: [ 1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x ]

    name: Tests - Go ${{ matrix.go-version }}

    steps:
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://speakeasybot:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run the tests
        run: go test ./...
